/*------------------------------------------------------------------------------
-- 개체 이름: MYBATIS.ATCHFILE
-- 만든 날짜: 2013-03-07 오후 5:21:56
-- 마지막으로 수정한 날짜: 2013-03-07 오후 5:21:56
-- 상태: VALID
------------------------------------------------------------------------------*/
DROP TABLE MYBATIS.ATCHFILE CASCADE CONSTRAINTS;

CREATE TABLE MYBATIS.ATCHFILE (
  F_GROUP        NUMBER                 NOT NULL, 
  F_ORDER        NUMBER                 NOT NULL, 
  F_PATH         VARCHAR2(400 BYTE)         NULL, 
  F_NAME_ORG     VARCHAR2(400 BYTE)         NULL, 
  F_NAME_SAV     VARCHAR2(400 BYTE)         NULL, 
  F_SIZE         VARCHAR2(50 BYTE)          NULL, 
  F_EXTENSION    VARCHAR2(10 BYTE)          NULL
)
TABLESPACE SYSTEM
PCTFREE    10
PCTUSED    40
INITRANS   1
MAXTRANS   255
STORAGE (
    INITIAL     64K
    NEXT        1M
    MINEXTENTS  1
    MAXEXTENTS  UNLIMITED
    FREELISTS   1
    FREELIST GROUPS 1
)
LOGGING
NOCACHE
MONITORING
NOPARALLEL
;

COMMENT ON TABLE MYBATIS.ATCHFILE IS '첨부파일';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_GROUP IS '파일그룹';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_ORDER IS '파일순서';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_PATH IS '경로';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_NAME_ORG IS '원래파일명';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_NAME_SAV IS '저장파일명';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_SIZE IS '파일 크기';

COMMENT ON COLUMN MYBATIS.ATCHFILE.F_EXTENSION IS '확장자';

ALTER TABLE MYBATIS.ATCHFILE ADD
(
    CONSTRAINT PK_ATCHFILE
    PRIMARY KEY ( F_GROUP, F_ORDER )
        USING INDEX
        TABLESPACE SYSTEM 
        PCTFREE 10
        INITRANS 2
        MAXTRANS 255
        STORAGE (
            INITIAL 64K
            NEXT 1M
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            FREELISTS 1
            FREELIST GROUPS 1
        )
);

